## Makemore

In [1]:
words = [
    "Massimo", "Liza", "Miriam", "Giorgio", "Whisky", "Dodo",
    "James", "Emma", "Oliver", "Sophia", "Liam", "Ava", "Noah", "Isabella",
    "Ethan", "Mia", "Lucas", "Charlotte", "Mason", "Amelia", "Logan", "Harper",
    "Alexander", "Evelyn", "Benjamin", "Abigail", "Elijah", "Emily", "William",
    "Elizabeth", "Henry", "Sofia", "Jacob", "Avery", "Michael", "Ella",
    "Daniel", "Scarlett", "Matthew", "Grace", "Jackson", "Chloe", "Sebastian",
    "Victoria", "David", "Riley", "Joseph", "Aria", "Samuel", "Lily", "Carter",
    "Aubrey", "Owen", "Zoey", "Wyatt", "Penelope", "John", "Hannah", "Luke",
    "Layla", "Gabriel", "Nora", "Anthony", "Ellie", "Isaac", "Madeline", "Jack",
    "Hazel", "Jayden", "Violet", "Dylan", "Aurora", "Nathan", "Stella", "Caleb",
    "Lucy", "Ryan", "Anna", "Andrew", "Caroline", "Joshua", "Genesis",
    "Christopher", "Aaliyah", "Thomas", "Kennedy", "Charles", "Kinsley", "Josiah",
    "Allison", "Isaiah", "Sarah", "Levi", "Maria", "Mateo", "Iris", "Julian",
    "Naomi", "Aaron", "Eliana", "Elias", "Jade", "Connor", "Clara", "Cameron",
    "Elena",
]

In [2]:
SPECIAL_TOKEN = "."

chars = []
for w in words:
    chars += [SPECIAL_TOKEN] + list(w)

chars

['.',
 'M',
 'a',
 's',
 's',
 'i',
 'm',
 'o',
 '.',
 'L',
 'i',
 'z',
 'a',
 '.',
 'M',
 'i',
 'r',
 'i',
 'a',
 'm',
 '.',
 'G',
 'i',
 'o',
 'r',
 'g',
 'i',
 'o',
 '.',
 'W',
 'h',
 'i',
 's',
 'k',
 'y',
 '.',
 'D',
 'o',
 'd',
 'o',
 '.',
 'J',
 'a',
 'm',
 'e',
 's',
 '.',
 'E',
 'm',
 'm',
 'a',
 '.',
 'O',
 'l',
 'i',
 'v',
 'e',
 'r',
 '.',
 'S',
 'o',
 'p',
 'h',
 'i',
 'a',
 '.',
 'L',
 'i',
 'a',
 'm',
 '.',
 'A',
 'v',
 'a',
 '.',
 'N',
 'o',
 'a',
 'h',
 '.',
 'I',
 's',
 'a',
 'b',
 'e',
 'l',
 'l',
 'a',
 '.',
 'E',
 't',
 'h',
 'a',
 'n',
 '.',
 'M',
 'i',
 'a',
 '.',
 'L',
 'u',
 'c',
 'a',
 's',
 '.',
 'C',
 'h',
 'a',
 'r',
 'l',
 'o',
 't',
 't',
 'e',
 '.',
 'M',
 'a',
 's',
 'o',
 'n',
 '.',
 'A',
 'm',
 'e',
 'l',
 'i',
 'a',
 '.',
 'L',
 'o',
 'g',
 'a',
 'n',
 '.',
 'H',
 'a',
 'r',
 'p',
 'e',
 'r',
 '.',
 'A',
 'l',
 'e',
 'x',
 'a',
 'n',
 'd',
 'e',
 'r',
 '.',
 'E',
 'v',
 'e',
 'l',
 'y',
 'n',
 '.',
 'B',
 'e',
 'n',
 'j',
 'a',
 'm',
 'i',
 'n',
 '.'

In [3]:
counts = {}
for pair in zip(chars, chars[1:]):
    counts[pair] = counts.get(pair, 0) + 1

counts

{('.', 'M'): 9,
 ('M', 'a'): 6,
 ('a', 's'): 6,
 ('s', 's'): 1,
 ('s', 'i'): 3,
 ('i', 'm'): 1,
 ('m', 'o'): 1,
 ('o', '.'): 4,
 ('.', 'L'): 9,
 ('L', 'i'): 3,
 ('i', 'z'): 2,
 ('z', 'a'): 2,
 ('a', '.'): 20,
 ('M', 'i'): 3,
 ('i', 'r'): 1,
 ('r', 'i'): 7,
 ('i', 'a'): 16,
 ('a', 'm'): 7,
 ('m', '.'): 3,
 ('.', 'G'): 4,
 ('G', 'i'): 1,
 ('i', 'o'): 3,
 ('o', 'r'): 5,
 ('r', 'g'): 1,
 ('g', 'i'): 1,
 ('.', 'W'): 3,
 ('W', 'h'): 1,
 ('h', 'i'): 2,
 ('i', 's'): 5,
 ('s', 'k'): 1,
 ('k', 'y'): 1,
 ('y', '.'): 12,
 ('.', 'D'): 4,
 ('D', 'o'): 1,
 ('o', 'd'): 1,
 ('d', 'o'): 1,
 ('.', 'J'): 11,
 ('J', 'a'): 6,
 ('m', 'e'): 3,
 ('e', 's'): 3,
 ('s', '.'): 7,
 ('.', 'E'): 11,
 ('E', 'm'): 2,
 ('m', 'm'): 1,
 ('m', 'a'): 2,
 ('.', 'O'): 2,
 ('O', 'l'): 1,
 ('l', 'i'): 13,
 ('i', 'v'): 1,
 ('v', 'e'): 3,
 ('e', 'r'): 7,
 ('r', '.'): 6,
 ('.', 'S'): 7,
 ('S', 'o'): 2,
 ('o', 'p'): 3,
 ('p', 'h'): 3,
 ('.', 'A'): 14,
 ('A', 'v'): 2,
 ('v', 'a'): 1,
 ('.', 'N'): 4,
 ('N', 'o'): 2,
 ('o', 'a'): 1,
 

In [4]:
sorted(counts.items(), key=lambda kv: kv[1], reverse=True)

[(('a', '.'), 20),
 (('n', '.'), 17),
 (('i', 'a'), 16),
 (('.', 'A'), 14),
 (('l', 'i'), 13),
 (('y', '.'), 12),
 (('.', 'J'), 11),
 (('.', 'E'), 11),
 (('e', 'l'), 11),
 (('a', 'n'), 11),
 (('.', 'C'), 10),
 (('a', 'r'), 10),
 (('.', 'M'), 9),
 (('.', 'L'), 9),
 (('h', '.'), 9),
 (('e', '.'), 9),
 (('l', 'e'), 8),
 (('e', 'n'), 8),
 (('r', 'i'), 7),
 (('a', 'm'), 7),
 (('s', '.'), 7),
 (('e', 'r'), 7),
 (('.', 'S'), 7),
 (('a', 'h'), 7),
 (('o', 'n'), 7),
 (('E', 'l'), 7),
 (('M', 'a'), 6),
 (('a', 's'), 6),
 (('J', 'a'), 6),
 (('r', '.'), 6),
 (('l', 'l'), 6),
 (('l', 'a'), 6),
 (('l', '.'), 6),
 (('o', 'r'), 5),
 (('i', 's'), 5),
 (('t', 'h'), 5),
 (('h', 'a'), 5),
 (('i', 'l'), 5),
 (('a', 'c'), 5),
 (('r', 'a'), 5),
 (('n', 'e'), 5),
 (('o', '.'), 4),
 (('.', 'G'), 4),
 (('.', 'D'), 4),
 (('.', 'N'), 4),
 (('.', 'I'), 4),
 (('C', 'h'), 4),
 (('t', 't'), 4),
 (('t', 'e'), 4),
 (('.', 'H'), 4),
 (('d', 'e'), 4),
 (('i', 'n'), 4),
 (('a', 't'), 4),
 (('e', 'y'), 4),
 (('J', 'o'), 4)

In [5]:
import torch

In [6]:
NUM_LETTERS = 26
NUM_SPECIAL = 1
NUM_TOKENS = NUM_LETTERS + NUM_SPECIAL

N = torch.zeros((NUM_TOKENS, NUM_TOKENS))
N

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
      

In [7]:

alphabet = list(bytes([list('a'.encode("utf-8"))[0] + i for i in range(NUM_LETTERS)]).decode('utf-8'))
alphabet

['a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z']

In [8]:
stoi = {c: i + 1 for i, c in enumerate(alphabet)}
stoi[SPECIAL_TOKEN] = 0
stoi

{'a': 1,
 'b': 2,
 'c': 3,
 'd': 4,
 'e': 5,
 'f': 6,
 'g': 7,
 'h': 8,
 'i': 9,
 'j': 10,
 'k': 11,
 'l': 12,
 'm': 13,
 'n': 14,
 'o': 15,
 'p': 16,
 'q': 17,
 'r': 18,
 's': 19,
 't': 20,
 'u': 21,
 'v': 22,
 'w': 23,
 'x': 24,
 'y': 25,
 'z': 26,
 '.': 0}

In [9]:
itos = {i: s for s, i in stoi.items()}
itos

{1: 'a',
 2: 'b',
 3: 'c',
 4: 'd',
 5: 'e',
 6: 'f',
 7: 'g',
 8: 'h',
 9: 'i',
 10: 'j',
 11: 'k',
 12: 'l',
 13: 'm',
 14: 'n',
 15: 'o',
 16: 'p',
 17: 'q',
 18: 'r',
 19: 's',
 20: 't',
 21: 'u',
 22: 'v',
 23: 'w',
 24: 'x',
 25: 'y',
 26: 'z',
 0: '.'}

In [10]:
for w in words:
    chars = [SPECIAL_TOKEN] + list(w.lower()) + [SPECIAL_TOKEN]
    for c1, c2 in zip(chars, chars[1:]):
        idx = stoi[c1]
        idy = stoi[c2]
        N[idx][idy] += 1

N

tensor([[ 0., 14.,  1., 10.,  4., 11.,  0.,  4.,  4.,  4., 11.,  2.,  9.,  9.,
          4.,  2.,  1.,  0.,  2.,  7.,  1.,  0.,  2.,  3.,  0.,  0.,  1.],
        [21.,  3.,  4.,  5.,  2.,  1.,  0.,  0.,  7.,  2.,  0.,  0.,  4.,  8.,
         14.,  1.,  0.,  0., 11.,  6.,  4.,  2.,  3.,  0.,  0.,  2.,  1.],
        [ 2.,  1.,  0.,  0.,  0.,  3.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  6.,  0.,  0.,  0.,  1.,  0.,  0.,  5.,  0.,  0.,  2.,  1.,  0.,
          0.,  2.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.],
        [ 1.,  2.,  0.,  0.,  0.,  4.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  2.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  0.],
        [ 9.,  0.,  2.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 18.,  2.,
          8.,  1.,  1.,  0.,  7.,  3.,  4.,  0.,  2.,  2.,  1.,  4.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0

In [11]:
p = N[0].float() / sum(N[0])
p

tensor([0.0000, 0.1321, 0.0094, 0.0943, 0.0377, 0.1038, 0.0000, 0.0377, 0.0377,
        0.0377, 0.1038, 0.0189, 0.0849, 0.0849, 0.0377, 0.0189, 0.0094, 0.0000,
        0.0189, 0.0660, 0.0094, 0.0000, 0.0189, 0.0283, 0.0000, 0.0000, 0.0094])

In [12]:
g = torch.Generator().manual_seed(214783647)
idx = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
itos[idx]


'e'

In [13]:
g = torch.Generator().manual_seed(214783647)

idx = 0
word = ""
while True:
    p = N[idx].float() / sum(N[idx])
    idx = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
    if idx == 0:
        break
    word += itos[idx]

word

'eyn'

In [14]:
P = N.float()
P /= P.sum(dim=1, keepdim=True)

P[0].sum()


tensor(1.)

In [15]:
g = torch.Generator().manual_seed(214783647)

idx = 0
word = ""
while True:
    p = P[idx]
    idx = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
    if idx == 0:
        break
    word += itos[idx]

word

'eyn'

In [16]:
log_likelyhood = 0.0
n = 0
for w in words:
    chars = [SPECIAL_TOKEN] + list(w.lower()) + [SPECIAL_TOKEN]
    for c1, c2 in zip(chars, chars[1:]):
        prob = P[stoi[c1]][stoi[c2]]
        logprob = torch.log(prob)
        log_likelyhood += logprob
        n += 1
        print(f"{c1}, {c2}: {logprob: .4f}")

nll = -log_likelyhood
print(nll/n)

., m: -2.4662
m, a: -1.0561
a, s: -2.8234
s, s: -3.4012
s, i: -2.3026
i, m: -3.9703
m, o: -3.1355
o, .: -2.2246
., l: -2.4662
l, i: -1.2164
i, z: -3.2771
z, a: -0.6931
a, .: -1.5706
., m: -2.4662
m, i: -1.3437
i, r: -3.2771
r, i: -1.4469
i, a: -1.1977
a, m: -2.5357
m, .: -2.0369
., g: -3.2771
g, i: -1.2528
i, o: -2.8717
o, r: -2.0015
r, g: -3.5264
g, i: -1.2528
i, o: -2.8717
o, .: -2.2246
., w: -3.5648
w, h: -1.7918
h, i: -2.6391
i, s: -1.8909
s, k: -3.4012
k, y: -1.7918
y, .: -0.4595
., d: -3.2771
d, o: -1.7918
o, d: -3.6109
d, o: -1.7918
o, .: -2.2246
., j: -2.2655
j, a: -0.4855
a, m: -2.5357
m, e: -2.0369
e, s: -3.0758
s, .: -1.4553
., e: -2.2655
e, m: -3.4812
m, m: -3.1355
m, a: -1.0561
a, .: -1.5706
., o: -3.9703
o, l: -2.5123
l, i: -1.2164
i, v: -3.9703
v, e: -0.9808
e, r: -2.2285
r, .: -1.7346
., s: -2.7175
s, o: -1.7918
o, p: -2.5123
p, h: -0.6931
h, i: -2.6391
i, a: -1.1977
a, .: -1.5706
., l: -2.4662
l, i: -1.2164
i, a: -1.1977
a, m: -2.5357
m, .: -2.0369
., a: -2.0244
a, v: 

In [17]:
xs, ys = [], []

for w in words:
    chars = [SPECIAL_TOKEN] + list(w.lower()) + [SPECIAL_TOKEN]
    for c1, c2 in zip(chars, chars[1:]):
        ix1 = stoi[c1]
        ix2 = stoi[c2]
        xs.append(ix1)
        ys.append(ix2)

for pair in zip(xs, ys):
    print(pair)

(0, 13)
(13, 1)
(1, 19)
(19, 19)
(19, 9)
(9, 13)
(13, 15)
(15, 0)
(0, 12)
(12, 9)
(9, 26)
(26, 1)
(1, 0)
(0, 13)
(13, 9)
(9, 18)
(18, 9)
(9, 1)
(1, 13)
(13, 0)
(0, 7)
(7, 9)
(9, 15)
(15, 18)
(18, 7)
(7, 9)
(9, 15)
(15, 0)
(0, 23)
(23, 8)
(8, 9)
(9, 19)
(19, 11)
(11, 25)
(25, 0)
(0, 4)
(4, 15)
(15, 4)
(4, 15)
(15, 0)
(0, 10)
(10, 1)
(1, 13)
(13, 5)
(5, 19)
(19, 0)
(0, 5)
(5, 13)
(13, 13)
(13, 1)
(1, 0)
(0, 15)
(15, 12)
(12, 9)
(9, 22)
(22, 5)
(5, 18)
(18, 0)
(0, 19)
(19, 15)
(15, 16)
(16, 8)
(8, 9)
(9, 1)
(1, 0)
(0, 12)
(12, 9)
(9, 1)
(1, 13)
(13, 0)
(0, 1)
(1, 22)
(22, 1)
(1, 0)
(0, 14)
(14, 15)
(15, 1)
(1, 8)
(8, 0)
(0, 9)
(9, 19)
(19, 1)
(1, 2)
(2, 5)
(5, 12)
(12, 12)
(12, 1)
(1, 0)
(0, 5)
(5, 20)
(20, 8)
(8, 1)
(1, 14)
(14, 0)
(0, 13)
(13, 9)
(9, 1)
(1, 0)
(0, 12)
(12, 21)
(21, 3)
(3, 1)
(1, 19)
(19, 0)
(0, 3)
(3, 8)
(8, 1)
(1, 18)
(18, 12)
(12, 15)
(15, 20)
(20, 20)
(20, 5)
(5, 0)
(0, 13)
(13, 1)
(1, 19)
(19, 15)
(15, 14)
(14, 0)
(0, 1)
(1, 13)
(13, 5)
(5, 12)
(12, 9)
(9, 1)
(1, 0)

In [18]:
import sys
from pathlib import Path

sys.path.insert(0, str(Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()))

In [19]:
from lib.mlp import MLP

mlp = MLP(NUM_TOKENS, [NUM_TOKENS])

In [20]:
x = "l"

# one hot encoding
xenc = [1.0 if i == stoi[x] else 0.0 for i in range(NUM_TOKENS)]
# exponentiate the outputs so they are all > 0
ypreds = [ypred.exp() for ypred in mlp(xenc)]
# normalize them so that they represent a probability distribution
probs = [y / sum(ypreds) for y in ypreds]
# get the most likely prediction
prob, ypred = max([(p, i) for i, p in enumerate(probs)])

print(f"predicted {itos[ypred]} with probability {prob.data}")

predicted r with probability 0.07717593520971862


In [21]:
class NLP(MLP):
    
    def get_probability(self, x, y):
        # one hot encoding
        xenc = [1.0 if i == x else 0.0 for i in range(NUM_TOKENS)]
        # exponentiate the outputs so they are all > 0
        ypreds = [ypred.exp() for ypred in self(xenc)]
        # normalize them so that they represent a probability distribution
        probs = [ypred / sum(ypreds) for ypred in ypreds]
        # return the probability of the expected output
        # we would like this probability to be high
        return probs[y]

    def train(self, xs, ys, iter, step):
        for _ in range(iter):
            # forward
            probs = [self.get_probability(x, y) for x, y in zip(xs, ys)]
            # likelyhood = product of probabilities
            # goal: maximize the likelyhood
            # to make sure the likelyhood is not too small we take the logarithm
            # log(p1 * p2) = log(p1) + log(p2)
            # for convenience, we consider the average of the logprobs instead of the sum
            # log of probabilities (<= 1) is <= 0
            # consider the negative log likelyhood as the loss to be minimized
            logprobs = [prob.log() for prob in probs]
            log_likelyhood = sum(logprobs) / len(logprobs)
            loss = -log_likelyhood
            print(f"loss {loss.data}")
            loss._label = "loss"
            loss.grad = 1
            self.zero_grad()
            # backward
            loss.backward()
            # update
            for p in self.parameters():
                p.data += p.grad * (-step)

In [22]:
nlp = NLP(NUM_TOKENS, [NUM_TOKENS])

In [23]:
nlp.train(xs, ys, 5, 10)

loss 3.406478255965957
loss 3.0039581470445302
loss 2.981037984338186
loss 2.9696265203593644
loss 2.961844675825764


In [24]:
import torch.nn.functional as F

In [25]:
xs = torch.tensor(xs)
ys = torch.tensor(ys)

In [26]:
g = torch.Generator().manual_seed(1234567890)
W = torch.randn((NUM_TOKENS, NUM_TOKENS), generator=g, requires_grad=True)

In [27]:
xenc = F.one_hot(xs, num_classes=NUM_TOKENS).float()
# predict log-counts
logits = xenc @ W
# softmax
counts = logits.exp()
# probabilities for the next character
probs = counts / counts.sum(1, keepdims=True)

In [28]:
# average negative log likelyhood
loss = -probs[torch.arange(len(xs)), ys].log().mean()
loss


tensor(3.7750, grad_fn=<NegBackward0>)

In [29]:
# set gradients to zero
W.grad = None
loss.backward()

In [30]:
W.grad

tensor([[ 5.7354e-03, -1.6681e-02,  2.3043e-03, -1.2240e-02, -4.2838e-03,
         -1.2296e-02,  6.4173e-03, -4.4630e-03,  8.1409e-04, -1.9442e-04,
         -6.7796e-03,  1.0303e-03, -5.5952e-03, -1.1706e-02, -2.6205e-03,
          3.8664e-03,  1.2281e-03,  5.2762e-03,  1.7601e-03, -6.6063e-03,
          6.7371e-03,  2.9839e-02,  2.4506e-03,  1.7712e-03,  1.3514e-03,
          3.6126e-03,  9.2715e-03],
        [-2.4224e-02, -2.5214e-03, -2.1469e-03, -5.5477e-03,  1.0068e-04,
          6.1555e-03,  2.9407e-03,  2.4124e-03, -5.2252e-03,  3.3409e-03,
          9.7347e-03,  2.6201e-03, -1.2822e-03, -8.5476e-03, -7.9721e-03,
          7.6481e-04,  1.1062e-02,  4.9218e-03, -1.4034e-02,  1.1534e-03,
          2.4860e-03,  1.4431e-03,  8.5359e-03,  7.6314e-03,  9.3144e-04,
          2.7243e-03,  2.5423e-03],
        [-2.4016e-03, -6.4220e-04,  4.7210e-04,  7.3623e-04,  1.9685e-04,
         -4.1289e-03,  2.1235e-04,  1.3603e-04,  8.5835e-05, -1.3124e-03,
          4.3839e-04,  2.7936e-04,  6.34

In [31]:
W.data += -0.1 * W.grad

In [32]:
for k in range(100):
    # forward
    xenc = F.one_hot(xs, num_classes=NUM_TOKENS).float()
    logits = xenc @ W
    counts = logits.exp()
    probs = counts / counts.sum(1, keepdims=True)
    loss = -probs[torch.arange(len(xs)), ys].log().mean()
    print(loss.data)

    # backward
    W.grad = None
    loss.backward()

    # update
    W.data += -50 * W.grad

tensor(3.7740)
tensor(3.3193)
tensor(3.0347)
tensor(2.8561)
tensor(2.7386)
tensor(2.6539)
tensor(2.5895)
tensor(2.5389)
tensor(2.4982)
tensor(2.4648)
tensor(2.4370)
tensor(2.4134)
tensor(2.3931)
tensor(2.3757)
tensor(2.3604)
tensor(2.3470)
tensor(2.3351)
tensor(2.3244)
tensor(2.3149)
tensor(2.3063)
tensor(2.2985)
tensor(2.2914)
tensor(2.2849)
tensor(2.2789)
tensor(2.2734)
tensor(2.2682)
tensor(2.2635)
tensor(2.2590)
tensor(2.2549)
tensor(2.2510)
tensor(2.2473)
tensor(2.2439)
tensor(2.2406)
tensor(2.2375)
tensor(2.2346)
tensor(2.2318)
tensor(2.2292)
tensor(2.2267)
tensor(2.2243)
tensor(2.2221)
tensor(2.2199)
tensor(2.2178)
tensor(2.2159)
tensor(2.2140)
tensor(2.2122)
tensor(2.2105)
tensor(2.2088)
tensor(2.2072)
tensor(2.2057)
tensor(2.2042)
tensor(2.2028)
tensor(2.2015)
tensor(2.2002)
tensor(2.1989)
tensor(2.1977)
tensor(2.1966)
tensor(2.1955)
tensor(2.1944)
tensor(2.1934)
tensor(2.1924)
tensor(2.1914)
tensor(2.1905)
tensor(2.1896)
tensor(2.1887)
tensor(2.1879)
tensor(2.1871)
tensor(2.1