## Makemore

In [221]:
words = [
    "Massimo", "Liza", "Miriam", "Giorgio", "Whisky", "Dodo",
    "James", "Emma", "Oliver", "Sophia", "Liam", "Ava", "Noah", "Isabella",
    "Ethan", "Mia", "Lucas", "Charlotte", "Mason", "Amelia", "Logan", "Harper",
    "Alexander", "Evelyn", "Benjamin", "Abigail", "Elijah", "Emily", "William",
    "Elizabeth", "Henry", "Sofia", "Jacob", "Avery", "Michael", "Ella",
    "Daniel", "Scarlett", "Matthew", "Grace", "Jackson", "Chloe", "Sebastian",
    "Victoria", "David", "Riley", "Joseph", "Aria", "Samuel", "Lily", "Carter",
    "Aubrey", "Owen", "Zoey", "Wyatt", "Penelope", "John", "Hannah", "Luke",
    "Layla", "Gabriel", "Nora", "Anthony", "Ellie", "Isaac", "Madeline", "Jack",
    "Hazel", "Jayden", "Violet", "Dylan", "Aurora", "Nathan", "Stella", "Caleb",
    "Lucy", "Ryan", "Anna", "Andrew", "Caroline", "Joshua", "Genesis",
    "Christopher", "Aaliyah", "Thomas", "Kennedy", "Charles", "Kinsley", "Josiah",
    "Allison", "Isaiah", "Sarah", "Levi", "Maria", "Mateo", "Iris", "Julian",
    "Naomi", "Aaron", "Eliana", "Elias", "Jade", "Connor", "Clara", "Cameron",
    "Elena",
]

In [222]:
SPECIAL_TOKEN = "."

chars = []
for w in words:
    chars += [SPECIAL_TOKEN] + list(w)

chars

['.',
 'M',
 'a',
 's',
 's',
 'i',
 'm',
 'o',
 '.',
 'L',
 'i',
 'z',
 'a',
 '.',
 'M',
 'i',
 'r',
 'i',
 'a',
 'm',
 '.',
 'G',
 'i',
 'o',
 'r',
 'g',
 'i',
 'o',
 '.',
 'W',
 'h',
 'i',
 's',
 'k',
 'y',
 '.',
 'D',
 'o',
 'd',
 'o',
 '.',
 'J',
 'a',
 'm',
 'e',
 's',
 '.',
 'E',
 'm',
 'm',
 'a',
 '.',
 'O',
 'l',
 'i',
 'v',
 'e',
 'r',
 '.',
 'S',
 'o',
 'p',
 'h',
 'i',
 'a',
 '.',
 'L',
 'i',
 'a',
 'm',
 '.',
 'A',
 'v',
 'a',
 '.',
 'N',
 'o',
 'a',
 'h',
 '.',
 'I',
 's',
 'a',
 'b',
 'e',
 'l',
 'l',
 'a',
 '.',
 'E',
 't',
 'h',
 'a',
 'n',
 '.',
 'M',
 'i',
 'a',
 '.',
 'L',
 'u',
 'c',
 'a',
 's',
 '.',
 'C',
 'h',
 'a',
 'r',
 'l',
 'o',
 't',
 't',
 'e',
 '.',
 'M',
 'a',
 's',
 'o',
 'n',
 '.',
 'A',
 'm',
 'e',
 'l',
 'i',
 'a',
 '.',
 'L',
 'o',
 'g',
 'a',
 'n',
 '.',
 'H',
 'a',
 'r',
 'p',
 'e',
 'r',
 '.',
 'A',
 'l',
 'e',
 'x',
 'a',
 'n',
 'd',
 'e',
 'r',
 '.',
 'E',
 'v',
 'e',
 'l',
 'y',
 'n',
 '.',
 'B',
 'e',
 'n',
 'j',
 'a',
 'm',
 'i',
 'n',
 '.'

In [223]:
counts = {}
for pair in zip(chars, chars[1:]):
    counts[pair] = counts.get(pair, 0) + 1

counts

{('.', 'M'): 9,
 ('M', 'a'): 6,
 ('a', 's'): 6,
 ('s', 's'): 1,
 ('s', 'i'): 3,
 ('i', 'm'): 1,
 ('m', 'o'): 1,
 ('o', '.'): 4,
 ('.', 'L'): 9,
 ('L', 'i'): 3,
 ('i', 'z'): 2,
 ('z', 'a'): 2,
 ('a', '.'): 20,
 ('M', 'i'): 3,
 ('i', 'r'): 1,
 ('r', 'i'): 7,
 ('i', 'a'): 16,
 ('a', 'm'): 7,
 ('m', '.'): 3,
 ('.', 'G'): 4,
 ('G', 'i'): 1,
 ('i', 'o'): 3,
 ('o', 'r'): 5,
 ('r', 'g'): 1,
 ('g', 'i'): 1,
 ('.', 'W'): 3,
 ('W', 'h'): 1,
 ('h', 'i'): 2,
 ('i', 's'): 5,
 ('s', 'k'): 1,
 ('k', 'y'): 1,
 ('y', '.'): 12,
 ('.', 'D'): 4,
 ('D', 'o'): 1,
 ('o', 'd'): 1,
 ('d', 'o'): 1,
 ('.', 'J'): 11,
 ('J', 'a'): 6,
 ('m', 'e'): 3,
 ('e', 's'): 3,
 ('s', '.'): 7,
 ('.', 'E'): 11,
 ('E', 'm'): 2,
 ('m', 'm'): 1,
 ('m', 'a'): 2,
 ('.', 'O'): 2,
 ('O', 'l'): 1,
 ('l', 'i'): 13,
 ('i', 'v'): 1,
 ('v', 'e'): 3,
 ('e', 'r'): 7,
 ('r', '.'): 6,
 ('.', 'S'): 7,
 ('S', 'o'): 2,
 ('o', 'p'): 3,
 ('p', 'h'): 3,
 ('.', 'A'): 14,
 ('A', 'v'): 2,
 ('v', 'a'): 1,
 ('.', 'N'): 4,
 ('N', 'o'): 2,
 ('o', 'a'): 1,
 

In [224]:
sorted(counts.items(), key=lambda kv: kv[1], reverse=True)

[(('a', '.'), 20),
 (('n', '.'), 17),
 (('i', 'a'), 16),
 (('.', 'A'), 14),
 (('l', 'i'), 13),
 (('y', '.'), 12),
 (('.', 'J'), 11),
 (('.', 'E'), 11),
 (('e', 'l'), 11),
 (('a', 'n'), 11),
 (('.', 'C'), 10),
 (('a', 'r'), 10),
 (('.', 'M'), 9),
 (('.', 'L'), 9),
 (('h', '.'), 9),
 (('e', '.'), 9),
 (('l', 'e'), 8),
 (('e', 'n'), 8),
 (('r', 'i'), 7),
 (('a', 'm'), 7),
 (('s', '.'), 7),
 (('e', 'r'), 7),
 (('.', 'S'), 7),
 (('a', 'h'), 7),
 (('o', 'n'), 7),
 (('E', 'l'), 7),
 (('M', 'a'), 6),
 (('a', 's'), 6),
 (('J', 'a'), 6),
 (('r', '.'), 6),
 (('l', 'l'), 6),
 (('l', 'a'), 6),
 (('l', '.'), 6),
 (('o', 'r'), 5),
 (('i', 's'), 5),
 (('t', 'h'), 5),
 (('h', 'a'), 5),
 (('i', 'l'), 5),
 (('a', 'c'), 5),
 (('r', 'a'), 5),
 (('n', 'e'), 5),
 (('o', '.'), 4),
 (('.', 'G'), 4),
 (('.', 'D'), 4),
 (('.', 'N'), 4),
 (('.', 'I'), 4),
 (('C', 'h'), 4),
 (('t', 't'), 4),
 (('t', 'e'), 4),
 (('.', 'H'), 4),
 (('d', 'e'), 4),
 (('i', 'n'), 4),
 (('a', 't'), 4),
 (('e', 'y'), 4),
 (('J', 'o'), 4)

In [225]:
import torch

In [226]:
NUM_LETTERS = 26
NUM_SPECIAL = 1
NUM_TOKENS = NUM_LETTERS + NUM_SPECIAL

N = torch.zeros((NUM_TOKENS, NUM_TOKENS))
N

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
      

In [227]:

alphabet = list(bytes([list('a'.encode("utf-8"))[0] + i for i in range(NUM_LETTERS)]).decode('utf-8'))
alphabet

['a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z']

In [228]:
stoi = {c: i + 1 for i, c in enumerate(alphabet)}
stoi[SPECIAL_TOKEN] = 0
stoi

{'a': 1,
 'b': 2,
 'c': 3,
 'd': 4,
 'e': 5,
 'f': 6,
 'g': 7,
 'h': 8,
 'i': 9,
 'j': 10,
 'k': 11,
 'l': 12,
 'm': 13,
 'n': 14,
 'o': 15,
 'p': 16,
 'q': 17,
 'r': 18,
 's': 19,
 't': 20,
 'u': 21,
 'v': 22,
 'w': 23,
 'x': 24,
 'y': 25,
 'z': 26,
 '.': 0}

In [229]:
itos = {i: s for s, i in stoi.items()}
itos

{1: 'a',
 2: 'b',
 3: 'c',
 4: 'd',
 5: 'e',
 6: 'f',
 7: 'g',
 8: 'h',
 9: 'i',
 10: 'j',
 11: 'k',
 12: 'l',
 13: 'm',
 14: 'n',
 15: 'o',
 16: 'p',
 17: 'q',
 18: 'r',
 19: 's',
 20: 't',
 21: 'u',
 22: 'v',
 23: 'w',
 24: 'x',
 25: 'y',
 26: 'z',
 0: '.'}

In [ ]:
for w in words:
    chars = [SPECIAL_TOKEN] + list(w.lower()) + [SPECIAL_TOKEN]
    for c1, c2 in zip(chars, chars[1:]):
        idx = stoi[c1]
        idy = stoi[c2]
        N[idx][idy] += 1

N

tensor([[ 0., 14.,  1., 10.,  4., 11.,  0.,  4.,  4.,  4., 11.,  2.,  9.,  9.,
          4.,  2.,  1.,  0.,  2.,  7.,  1.,  0.,  2.,  3.,  0.,  0.,  1.],
        [21.,  3.,  4.,  5.,  2.,  1.,  0.,  0.,  7.,  2.,  0.,  0.,  4.,  8.,
         14.,  1.,  0.,  0., 11.,  6.,  4.,  2.,  3.,  0.,  0.,  2.,  1.],
        [ 2.,  1.,  0.,  0.,  0.,  3.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  6.,  0.,  0.,  0.,  1.,  0.,  0.,  5.,  0.,  0.,  2.,  1.,  0.,
          0.,  2.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.],
        [ 1.,  2.,  0.,  0.,  0.,  4.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  2.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  0.],
        [ 9.,  0.,  2.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 18.,  2.,
          8.,  1.,  1.,  0.,  7.,  3.,  4.,  0.,  2.,  2.,  1.,  4.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0

In [231]:
p = N[0].float() / sum(N[0])
p

tensor([0.0000, 0.1321, 0.0094, 0.0943, 0.0377, 0.1038, 0.0000, 0.0377, 0.0377,
        0.0377, 0.1038, 0.0189, 0.0849, 0.0849, 0.0377, 0.0189, 0.0094, 0.0000,
        0.0189, 0.0660, 0.0094, 0.0000, 0.0189, 0.0283, 0.0000, 0.0000, 0.0094])

In [232]:
g = torch.Generator().manual_seed(214783647)
idx = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
itos[idx]


'e'

In [233]:
g = torch.Generator().manual_seed(214783647)

idx = 0
word = ""
while True:
    p = N[idx].float() / sum(N[idx])
    idx = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
    if idx == 0:
        break
    word += itos[idx]

word

'eyn'