## Neural Probabilistic Language Model

In [72]:
words = [
    "Massimo", "Liza", "Miriam", "Giorgio", "Whisky", "Dodo",
    "James", "Emma", "Oliver", "Sophia", "Liam", "Ava", "Noah", "Isabella",
    "Ethan", "Mia", "Lucas", "Charlotte", "Mason", "Amelia", "Logan", "Harper",
    "Alexander", "Evelyn", "Benjamin", "Abigail", "Elijah", "Emily", "William",
    "Elizabeth", "Henry", "Sofia", "Jacob", "Avery", "Michael", "Ella",
    "Daniel", "Scarlett", "Matthew", "Grace", "Jackson", "Chloe", "Sebastian",
    "Victoria", "David", "Riley", "Joseph", "Aria", "Samuel", "Lily", "Carter",
    "Aubrey", "Owen", "Zoey", "Wyatt", "Penelope", "John", "Hannah", "Luke",
    "Layla", "Gabriel", "Nora", "Anthony", "Ellie", "Isaac", "Madeline", "Jack",
    "Hazel", "Jayden", "Violet", "Dylan", "Aurora", "Nathan", "Stella", "Caleb",
    "Lucy", "Ryan", "Anna", "Andrew", "Caroline", "Joshua", "Genesis",
    "Christopher", "Aaliyah", "Thomas", "Kennedy", "Charles", "Kinsley", "Josiah",
    "Allison", "Isaiah", "Sarah", "Levi", "Maria", "Mateo", "Iris", "Julian",
    "Naomi", "Aaron", "Eliana", "Elias", "Jade", "Connor", "Clara", "Cameron",
    "Elena",
]

In [73]:
NUM_LETTERS = 26
NUM_SPECIAL = 1
NUM_TOKENS = NUM_LETTERS + NUM_SPECIAL

alphabet = list(bytes([list('a'.encode("utf-8"))[0] + i for i in range(NUM_LETTERS)]).decode('utf-8'))

stoi = {
    ".": 0
}
itos = {
    0: "."
}
for i, s in enumerate(alphabet):
    stoi[s] = i + 1
    itos[i + 1] = s

itos

{0: '.',
 1: 'a',
 2: 'b',
 3: 'c',
 4: 'd',
 5: 'e',
 6: 'f',
 7: 'g',
 8: 'h',
 9: 'i',
 10: 'j',
 11: 'k',
 12: 'l',
 13: 'm',
 14: 'n',
 15: 'o',
 16: 'p',
 17: 'q',
 18: 'r',
 19: 's',
 20: 't',
 21: 'u',
 22: 'v',
 23: 'w',
 24: 'x',
 25: 'y',
 26: 'z'}

In [74]:
import torch

CONTEXT_SIZE = 3
X, Y = [], []

for w in words:
    w = w.lower()
    print(w)
    context = [0] * CONTEXT_SIZE
    for s in w + ".":
        i = stoi[s]
        X.append(context)
        Y.append(i)
        print(f"{[itos[i] for i in context]} -> {s}")
        context = context[1:] + [i]

X = torch.tensor(X)
Y = torch.tensor(Y)

massimo
['.', '.', '.'] -> m
['.', '.', 'm'] -> a
['.', 'm', 'a'] -> s
['m', 'a', 's'] -> s
['a', 's', 's'] -> i
['s', 's', 'i'] -> m
['s', 'i', 'm'] -> o
['i', 'm', 'o'] -> .
liza
['.', '.', '.'] -> l
['.', '.', 'l'] -> i
['.', 'l', 'i'] -> z
['l', 'i', 'z'] -> a
['i', 'z', 'a'] -> .
miriam
['.', '.', '.'] -> m
['.', '.', 'm'] -> i
['.', 'm', 'i'] -> r
['m', 'i', 'r'] -> i
['i', 'r', 'i'] -> a
['r', 'i', 'a'] -> m
['i', 'a', 'm'] -> .
giorgio
['.', '.', '.'] -> g
['.', '.', 'g'] -> i
['.', 'g', 'i'] -> o
['g', 'i', 'o'] -> r
['i', 'o', 'r'] -> g
['o', 'r', 'g'] -> i
['r', 'g', 'i'] -> o
['g', 'i', 'o'] -> .
whisky
['.', '.', '.'] -> w
['.', '.', 'w'] -> h
['.', 'w', 'h'] -> i
['w', 'h', 'i'] -> s
['h', 'i', 's'] -> k
['i', 's', 'k'] -> y
['s', 'k', 'y'] -> .
dodo
['.', '.', '.'] -> d
['.', '.', 'd'] -> o
['.', 'd', 'o'] -> d
['d', 'o', 'd'] -> o
['o', 'd', 'o'] -> .
james
['.', '.', '.'] -> j
['.', '.', 'j'] -> a
['.', 'j', 'a'] -> m
['j', 'a', 'm'] -> e
['a', 'm', 'e'] -> s
['m', 'e'

In [75]:
import torch

EMBEDDING_SIZE = 2

g = torch.Generator().manual_seed(1)

# 2-dimensional embedding for each character
C = torch.randn((NUM_TOKENS, EMBEDDING_SIZE), generator=g)
C

tensor([[-1.5256, -0.7502],
        [-0.6540, -1.6095],
        [-0.1002, -0.6092],
        [-0.9798, -1.6091],
        [-0.7121,  0.3037],
        [-0.7773, -0.2515],
        [-0.2223,  1.6871],
        [ 0.2284,  0.4676],
        [-0.6970, -1.1608],
        [ 0.6995,  0.1991],
        [ 0.8657,  0.2444],
        [-0.6629,  0.8073],
        [ 1.1017, -0.1759],
        [-2.2456, -1.4465],
        [ 0.0612, -0.6177],
        [-0.7981, -0.1316],
        [ 1.8793, -0.0721],
        [ 0.1578, -0.7735],
        [ 0.1991,  0.0457],
        [ 1.1651,  2.0154],
        [ 0.2152, -0.5242],
        [-1.8034, -1.3083],
        [ 0.4533,  1.1422],
        [-3.3312, -0.7479],
        [ 1.1173,  0.2981],
        [ 0.1099, -0.6463],
        [ 0.4285,  1.4761]])

In [76]:
# embedding of the 5th character
C[5]

tensor([-0.7773, -0.2515])

In [77]:
# can index by list
C[[5, 6]]

tensor([[-0.7773, -0.2515],
        [-0.2223,  1.6871]])

In [78]:
# or even by a tensor to get the embeddings corresponding to the characters in each context
emb = C[X]
emb

tensor([[[-1.5256, -0.7502],
         [-1.5256, -0.7502],
         [-1.5256, -0.7502]],

        [[-1.5256, -0.7502],
         [-1.5256, -0.7502],
         [-2.2456, -1.4465]],

        [[-1.5256, -0.7502],
         [-2.2456, -1.4465],
         [-0.6540, -1.6095]],

        ...,

        [[-0.7773, -0.2515],
         [ 1.1017, -0.1759],
         [-0.7773, -0.2515]],

        [[ 1.1017, -0.1759],
         [-0.7773, -0.2515],
         [ 0.0612, -0.6177]],

        [[-0.7773, -0.2515],
         [ 0.0612, -0.6177],
         [-0.6540, -1.6095]]])

In [79]:
NUM_HIDDED_NEURONS = 100

g = torch.Generator().manual_seed(1)

W1 = torch.randn((CONTEXT_SIZE * EMBEDDING_SIZE), NUM_HIDDED_NEURONS, generator=g)
b1 = torch.randn(NUM_HIDDED_NEURONS, generator=g)

In [80]:
torch.cat([emb[:, 0, :], emb[:, 1, :], emb[:, 2, :]], 1)

tensor([[-1.5256, -0.7502, -1.5256, -0.7502, -1.5256, -0.7502],
        [-1.5256, -0.7502, -1.5256, -0.7502, -2.2456, -1.4465],
        [-1.5256, -0.7502, -2.2456, -1.4465, -0.6540, -1.6095],
        ...,
        [-0.7773, -0.2515,  1.1017, -0.1759, -0.7773, -0.2515],
        [ 1.1017, -0.1759, -0.7773, -0.2515,  0.0612, -0.6177],
        [-0.7773, -0.2515,  0.0612, -0.6177, -0.6540, -1.6095]])

In [81]:
torch.unbind(emb, 1)

(tensor([[-1.5256, -0.7502],
         [-1.5256, -0.7502],
         [-1.5256, -0.7502],
         ...,
         [-0.7773, -0.2515],
         [ 1.1017, -0.1759],
         [-0.7773, -0.2515]]),
 tensor([[-1.5256, -0.7502],
         [-1.5256, -0.7502],
         [-2.2456, -1.4465],
         ...,
         [ 1.1017, -0.1759],
         [-0.7773, -0.2515],
         [ 0.0612, -0.6177]]),
 tensor([[-1.5256, -0.7502],
         [-2.2456, -1.4465],
         [-0.6540, -1.6095],
         ...,
         [-0.7773, -0.2515],
         [ 0.0612, -0.6177],
         [-0.6540, -1.6095]]))

In [82]:
torch.cat(torch.unbind(emb, 1), 1)

tensor([[-1.5256, -0.7502, -1.5256, -0.7502, -1.5256, -0.7502],
        [-1.5256, -0.7502, -1.5256, -0.7502, -2.2456, -1.4465],
        [-1.5256, -0.7502, -2.2456, -1.4465, -0.6540, -1.6095],
        ...,
        [-0.7773, -0.2515,  1.1017, -0.1759, -0.7773, -0.2515],
        [ 1.1017, -0.1759, -0.7773, -0.2515,  0.0612, -0.6177],
        [-0.7773, -0.2515,  0.0612, -0.6177, -0.6540, -1.6095]])

In [83]:
emb.view(emb.shape[0], CONTEXT_SIZE * EMBEDDING_SIZE)

tensor([[-1.5256, -0.7502, -1.5256, -0.7502, -1.5256, -0.7502],
        [-1.5256, -0.7502, -1.5256, -0.7502, -2.2456, -1.4465],
        [-1.5256, -0.7502, -2.2456, -1.4465, -0.6540, -1.6095],
        ...,
        [-0.7773, -0.2515,  1.1017, -0.1759, -0.7773, -0.2515],
        [ 1.1017, -0.1759, -0.7773, -0.2515,  0.0612, -0.6177],
        [-0.7773, -0.2515,  0.0612, -0.6177, -0.6540, -1.6095]])

In [84]:
emb.view(-1, CONTEXT_SIZE * EMBEDDING_SIZE)

tensor([[-1.5256, -0.7502, -1.5256, -0.7502, -1.5256, -0.7502],
        [-1.5256, -0.7502, -1.5256, -0.7502, -2.2456, -1.4465],
        [-1.5256, -0.7502, -2.2456, -1.4465, -0.6540, -1.6095],
        ...,
        [-0.7773, -0.2515,  1.1017, -0.1759, -0.7773, -0.2515],
        [ 1.1017, -0.1759, -0.7773, -0.2515,  0.0612, -0.6177],
        [-0.7773, -0.2515,  0.0612, -0.6177, -0.6540, -1.6095]])

In [85]:
h = torch.tanh(emb.view(-1, CONTEXT_SIZE * EMBEDDING_SIZE) @ W1 + b1)
print(h.shape)
h

torch.Size([714, 100])


tensor([[ 0.8937,  0.9984,  0.9973,  ...,  0.9339,  0.2697,  0.9530],
        [ 0.7741,  0.9999,  0.9993,  ...,  0.9346,  0.8228,  0.9836],
        [ 0.9046,  0.7093,  0.9983,  ...,  0.9882,  0.5145,  1.0000],
        ...,
        [ 0.3868,  0.9997, -0.8151,  ...,  0.8285,  0.9240,  0.8658],
        [-0.8052, -0.0191, -0.9239,  ...,  0.9988,  0.7783,  0.5079],
        [ 0.4224,  0.9961, -0.1464,  ...,  0.9534,  0.9700,  0.9999]])

In [86]:
g = torch.Generator().manual_seed(1)

W2 = torch.randn(NUM_HIDDED_NEURONS, NUM_TOKENS, generator=g)
b2 = torch.randn(NUM_TOKENS, generator=g)

In [87]:
logits = h @ W2 + b2
print(logits.shape)
logits

torch.Size([714, 27])


tensor([[ 10.5673,   1.9202,  10.0856,  ...,  13.4272,  -0.4598, -15.1659],
        [  9.6933,   4.2117,   9.1245,  ...,  12.2753,   3.0510, -12.9140],
        [  8.3842,  -2.3130,  12.2655,  ...,   6.8975,  -5.8577, -13.2694],
        ...,
        [  5.2650,  -6.1616,   7.4143,  ...,  -3.8606,   0.9488,  11.1031],
        [  1.2296,  -9.3566,  -2.3346,  ...,   1.3420,  -3.6076,  -9.1437],
        [ 11.1515,  -4.2474,   9.1769,  ...,   0.1184,  -6.4374,   2.6228]])

In [88]:
counts = logits.exp()
prob = counts / counts.sum(1, keepdims = True)
prob

tensor([[4.9861e-02, 8.7574e-06, 3.0801e-02,  ..., 8.7056e-01, 8.1052e-07,
         3.3265e-13],
        [4.3060e-02, 1.7924e-04, 2.4380e-02,  ..., 5.6936e-01, 5.6147e-05,
         6.5439e-12],
        [1.5996e-02, 3.6165e-07, 7.7563e-01,  ..., 3.6172e-03, 1.0444e-08,
         6.3095e-12],
        ...,
        [2.8756e-06, 3.1348e-11, 2.4671e-05,  ..., 3.1299e-10, 3.8392e-08,
         9.8675e-04],
        [3.3170e-05, 8.3795e-10, 9.3944e-07,  ..., 3.7116e-05, 2.6302e-07,
         1.0368e-09],
        [8.5507e-01, 1.7551e-07, 1.1870e-01,  ..., 1.3815e-05, 1.9644e-08,
         1.6905e-04]])

In [89]:
log_likelyhood = prob[torch.arange(prob.shape[0]), Y].log().mean()
nll = -log_likelyhood
nll

tensor(15.1543)

In [90]:
import torch.nn.functional as F

# efficient way of computing the nll out of the box
F.cross_entropy(logits, Y)

tensor(15.1543)

In [95]:
# training
parameters = [C, W1, b1, W2, b2]

for p in parameters:
    p.requires_grad = True

for i in range(100):
    # forward
    emb = C[X]
    h = torch.tanh(emb.view(-1, CONTEXT_SIZE * EMBEDDING_SIZE) @ W1 + b1)
    logits = h @ W2 + b2
    loss = F.cross_entropy(logits, Y)
    print(loss.item())

    # backward
    for p in parameters:
        p.grad = None
    loss.backward()

    # update
    for p in parameters:
        p.data += -0.1 * p.grad
    

2.3875293731689453
2.261261463165283
2.174978494644165
2.113556385040283
2.0693862438201904
2.0378339290618896
2.01564621925354
2.000323534011841
1.989888310432434
1.9828070402145386
1.9779510498046875
1.9745357036590576
1.9720416069030762
1.9701355695724487
1.9686082601547241
1.9673292636871338
1.9662160873413086
1.965217113494873
1.9642995595932007
1.963441252708435
1.9626283645629883
1.9618507623672485
1.9611016511917114
1.960376262664795
1.9596703052520752
1.9589817523956299
1.958308219909668
1.9576480388641357
1.9570001363754272
1.9563629627227783
1.955735683441162
1.9551178216934204
1.9545083045959473
1.9539066553115845
1.9533125162124634
1.9527252912521362
1.9521445035934448
1.9515702724456787
1.951001763343811
1.9504389762878418
1.9498809576034546
1.9493285417556763
1.9487807750701904
1.9482377767562866
1.9476991891860962
1.947164535522461
1.9466345310211182
1.9461082220077515
1.9455857276916504
1.9450668096542358
1.9445518255233765
1.9440401792526245
1.9435317516326904
1.94302